name: 'Run swiftlint with reviewdog'
description: '🐶 Run swiftlint with reviewdog on pull requests to improve code review experience.'
author: 'ittybittyapps'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    default: '${{ github.token }}'
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'error'
  reporter:
    description: 'Reporter of reviewdog command [github-pr-check,github-pr-review].'
    default: 'github-pr-check'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'check'
  color: 'blue'
